import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

const dmSans = DM_Sans({ 
  subsets: ["latin"],
  variable: '--font-dm-sans', 
  display: "swap",
  weight: ["300", "400", "500", "600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
    <html lang="en">
      <body className={`${dmSans.variable} ${inter.variable} font-dmSans`}>
        {children}
      </body>
    </html>
    </Layout>
  );
}
